### ISSUE TITLE
How to properly use transaction.

### ISSUE THREAD

**Issue by stephen-dahl** [kubemq-io/kubemq-node#5]
I am following the Transactional Queue - Ack and reject example. 
Whenever transaction.closeStream(); is called the error handler is immediately called with this error
```
Error: 1 CANCELLED: Cancelled
    at Object.exports.createStatusError (c:\Users\steph\PhpstormProjects\response-rollup-loader\node_modules\grpc\src\common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (c:\Users\steph\PhpstormProjects\response-rollup-loader\node_modules\grpc\src\client.js:233:26)
    at ClientDuplexStream._readsDone (c:\Users\steph\PhpstormProjects\response-rollup-loader\node_modules\grpc\src\client.js:199:8)
    at c:\Users\steph\PhpstormProjects\response-rollup-loader\node_modules\grpc\src\client_interceptors.js:683:15
```

Is there more that needs to happen after the message has been ack'd?

**Comment by eitam-ring** [comment]
Hey,
You are receiving "CANCELLED: Cancelled" when calling transaction.closeStream(); since the stream is closed.

**Comment by stephen-dahl** [comment]
I just would not expect to receive an error when properly closing a stream
